name: Deploy S3

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.aws.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.aws.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Sync with S3
      run: |
        aws s3 sync . s3://portfolio.alvesguilherme.com
